title: Aeromat Documentation
description: Technical documentation for performance plastics manufacturing
baseurl: ""
url: "https://docs.aeromat.io"

# Theme settings
theme: null
markdown: kramdown
highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
      nav_order: 1

# Build settings
sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation Structure
nav_sections:
  - title: Home
    items:
      - overview
      - about
      - contact
      - style-guide
  - title: Materials
    items:
      - title: Overview
        path: materials/index
      - title: Acetal
        items:
          - title: Copolymer (POM-C)
            items:
              - acetal-copolymer
              - anti-static
              - conductive
              - glass-filled
          - title: Homopolymer (Delrin®)
            items:
              - acetal-homopolymer
              - glass-filled
              - ptfe-filled
          - material-guide
      - title: Acrylic
        items:
          - cast
          - extruded
          - impact-modified
          - material-guide
      - title: CPVC
        items:
          - high-temperature
          - material-guide
      - title: Nylon
        items:
          - nylon-6
          - nylon-66
          - material-guide
      - title: PEEK
        items:
          - glass-filled
          - carbon-filled
          - unfilled
          - material-guide
      - title: PET
        items:
          - pet-g
          - pet-t
          - material-guide
      - title: Polycarbonate
        items:
          - standard
          - uv-stabilized
          - glass-filled
          - material-guide
      - title: Polyethylene
        items:
          - ldpe
          - hdpe
          - hmw
          - uhmw
          - material-guide
      - title: Polypropylene
        items:
          - copolymer
          - homopolymer
          - material-guide
      - title: PTFE
        items:
          - virgin
          - title: Filled PTFE
            items:
              - glass-filled
              - carbon-filled
              - bronze-filled
          - material-guide
      - title: PVC
        items:
          - type-a
          - type-b
          - material-guide
      - title: PVDF
        items:
          - high-purity
          - chemical-resistant
          - material-guide
  - title: Design Guides
    items:
      - overview
      - plastic-design
      - fastener-design
  - title: Machining
    items:
      - overview
      - cnc-techniques
      - plastics
  - title: Welding
    items:
      - overview
      - plastic-techniques
      - materials

# Theme Configuration
theme_settings:
  # Colors (Material Design 3 Dark Theme)
  colors:
    primary: "#4F78FF"
    surface: "#121212"
    surface_variant: "#1E1E1E"
    on_surface: "#E1E1E1"
    on_surface_variant: "#B3B3B3"
  
  # Typography
  fonts:
    body: "Inter, system-ui, -apple-system, sans-serif"
    code: "JetBrains Mono, monospace" 